const dimensions=['目标力','专注力','自信力','适应力','抗挫力','情绪力'];
const abilityMap=[['M',1],['Q',1],['Z',1],['K',1],['S',1],['K',1],['M',-1],['X',-1],['Z',1],['Q',1],['S',-1],['X',-1],['M',-1],['Q',-1],['Z',-1],['K',-1],['S',-1],['K',-1],['M',1],['X',1],['Z',-1],['Q',-1],['S',1],['X',1]];
const abilityIndex={M:0,Z:1,X:2,S:3,K:4,Q:5};
const palette=[['#cfe8ff','#7fc4ff'],['#ffe0ea','#ff9abc'],['#e5dcff','#aa93ff'],['#fff0c7','#ffc866'],['#d8f7e5','#6ed6a0'],['#ffe2ce','#ff9b68']];
const raw=[['方向清晰','🧭','知道自己要去哪里',0,3],['蓄势待发','🌱','新的力量正在萌芽',2,5],['内心安定','🧘','允许自己慢下来',4,5],['专心投入','🎯','沉浸在重要之事中',1,2],['轻盈自在','🪽','与当下和谐共处',4,3],['勇敢表达','📣','让真实的声音被听见',3,2],['迷雾徘徊','🌫️','暂时看不清下一步',0,4],['电量不足','🔋','身心正在提醒你休息',2,5],['需要拥抱','🫂','渴望稳定的连接',3,4],['思绪纷飞','🌀','脑海里同时开着许多窗口',1,4],['稳步向前','🚶','按自己的节奏持续行动',2,0],['独处充电','🌙','从安静里找回自己',4,5],['目标坚定','⛰️','愿意攀登心中的高峰',0,2],['热情燃烧','🔥','被喜爱的事情点亮',2,4],['柔软连接','🤝','关系带来温暖与支持',3,5],['容易分心','🦋','注意力正在四处游走',1,0],['从容应对','🌊','允许变化自然发生',5,4],['压力满格','⏳','承担了太多未完成',4,1],['灵感涌现','💡','新的想法不断来到',1,0],['界限清晰','🛡️','懂得保护时间与能量',3,0],['反复纠结','🧶','需要一个更简单的答案',1,4],['焦虑紧张','🌧️','对未知保持着警觉',4,5],['灵活变通','🪁','能在变化中调整方向',5,0],['不骄不躁','🍵','稳定地做好眼前的事',1,5]];
const cards=raw.map((x,i)=>({id:i+1,title:x[0],icon:x[1],desc:x[2],ability:abilityMap[i][0],sign:abilityMap[i][1],colors:palette[i%palette.length]}));
let selected=[],groups=[[],[],[]],active=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function mini(c){return `<span class="mini" data-id="${c.id}" style="--c1:${c.colors[0]};--c2:${c.colors[1]}" title="${c.title}">${c.icon}</span>`}
function cardGroup(id){return groups.findIndex(g=>g.includes(id))}
function renderCards(){ $('#cards').innerHTML=cards.map(c=>{let gi=cardGroup(c.id),labels=['非常','比较','偶尔'],order=gi>-1?groups[gi].indexOf(c.id)+1:0;return `<button class="life-card ${gi>-1?'selected group-'+gi:''}" data-id="${c.id}" aria-label="${c.id}号卡牌：${c.title}${gi>-1?'，'+labels[gi]+'第'+order+'张':''}" title="${c.id}号 · ${c.title}"><span class="card-number">${c.id}</span>${gi>-1?`<span class="category-label">${labels[gi]} ${order}/4</span>`:''}</button>`}).join(''); $$('.life-card').forEach(el=>el.onclick=()=>toggle(+el.dataset.id)); }
function toggle(id){let current=cardGroup(id);if(current>-1){groups[current]=groups[current].filter(x=>x!==id)}else{let next=groups.findIndex(g=>g.length<4);if(next===-1){toast('已经选满 12 张卡牌');return}groups[next].push(id)}selected=groups.flat();renderCards();updateProgress();}
function updateProgress(){let n=selected.length;$('#countText').textContent=`已标记 ${n} / 12`;$('#progressBar').style.width=`${n/12*100}%`;$('#veryCount').textContent=`${groups[0].length} / 4`;$('#fairlyCount').textContent=`${groups[1].length} / 4`;$('#sometimesCount').textContent=`${groups[2].length} / 4`;$('#toSort').disabled=!groups.every(g=>g.length===4);}
$('#toSort').onclick=generate;
function show(id){$$('.stage').forEach(x=>x.classList.add('hidden'));$('#'+id).classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
function renderSort(){let assigned=groups.flat();let pool=selected.filter(id=>!assigned.includes(id)).map(id=>cards[id-1]);$('#selectedPool').innerHTML=pool.map(mini).join('');$$('#selectedPool .mini').forEach(el=>el.onclick=()=>{active=+el.dataset.id;renderSort()});$$('.bucket').forEach((b,i)=>{b.querySelector('.bucket-items').innerHTML=groups[i].map(id=>mini(cards[id-1])).join('');b.querySelector('.bucket-count').textContent=`${groups[i].length} / 4`;b.onclick=e=>{let remove=e.target.closest('.mini');if(remove){let id=+remove.dataset.id;groups[i]=groups[i].filter(x=>x!==id);active=id;renderSort();return}if(active&&groups[i].length<4){groups[i].push(active);active=null;renderSort()}}});if(active){let el=$(`#selectedPool .mini[data-id="${active}"]`);el&&el.classList.add('active')}$('#generate').disabled=!groups.every(g=>g.length===4)}
$('#generate').onclick=generate;
function generate(){let score=Array(6).fill(0),weights=[5,3,1];groups.forEach((g,gi)=>g.forEach(id=>{let c=cards[id-1];score[abilityIndex[c.ability]]+=c.sign*weights[gi]}));let top=score.indexOf(Math.max(...score)),titles=['方向笃定的航行者','深度专注的创造者','相信自己的实践者','灵活从容的适应者','坚韧生长的复原者','温柔敏锐的觉察者'];$('#resultTitle').textContent=titles[top];$('#resultSummary').textContent=`本次选择中，你得分最高的是「${dimensions[top]}」（${signed(score[top])}）。雷达图以 0 分虚线为基准，向外表示正向得分，向内表示负向得分。`;drawRadar(score);let order=score.map((v,i)=>[v,i]).sort((a,b)=>b[0]-a[0]);$('#insights').innerHTML=order.map(([v,i])=>`<div class="insight"><score class="${v<0?'negative':''}">${signed(v)}</score><b>${dimensions[i]}</b><p>${v>5?'这是你当下较为突出的生命资源。':v>=0?'这项能力目前处于相对平稳的状态。':'这项能力当前得分偏低，可以作为接下来关注的方向。'}</p></div>`).join('');$('#quote').textContent='“分数不是结论，而是一张帮助你看见当下的地图。”';$('#resultStage').classList.remove('hidden');$('#stepText').textContent='第二步 · 查看画像';$('#countText').textContent='测评完成';$('#progressBar').style.width='100%';$('#resultStage').scrollIntoView({behavior:'smooth',block:'start'})}
function signed(v){return v>0?`+${v}`:`${v}`}
function drawRadar(vals){let svg=$('#radar'),cx=260,cy=210,R=142,n=6,pt=(i,r)=>[cx+Math.sin(i*Math.PI/3)*r,cy-Math.cos(i*Math.PI/3)*r],poly=r=>Array.from({length:n},(_,i)=>pt(i,r).join(',')).join(' '),radius=v=>R*Math.max(0,Math.min(1,(v+20)/40));let grid=[.25,.5,.75,1].map(x=>`<polygon points="${poly(R*x)}" fill="none" stroke="#e1e7f0"/>`).join(''),zero=`<polygon points="${poly(R*.5)}" fill="none" stroke="#d05b7b" stroke-width="2" stroke-dasharray="7 7"/>`;let axes=dimensions.map((d,i)=>{let [x,y]=pt(i,R+42),[ax,ay]=pt(i,R),color=vals[i]<0?'#ef4444':'#16b77b';return `<line x1="${cx}" y1="${cy}" x2="${ax}" y2="${ay}" stroke="#e1e7f0"/><text x="${x}" y="${y}" text-anchor="middle" font-size="15" font-weight="700" fill="#172033">${d}</text><text x="${x}" y="${y+20}" text-anchor="middle" font-size="18" font-weight="800" fill="${color}">${signed(vals[i])}</text>`}).join('');let points=vals.map((v,i)=>pt(i,radius(v)).join(',')).join(' ');svg.innerHTML=grid+zero+axes+`<polygon points="${points}" fill="rgba(53,109,243,.18)" stroke="#356df3" stroke-width="4"/>`+vals.map((v,i)=>{let [x,y]=pt(i,radius(v)),color=v<0?'#ef4444':'#16b77b';return `<circle cx="${x}" cy="${y}" r="6" fill="white" stroke="${color}" stroke-width="4"/>`}).join('')}
function reset(){selected=[];groups=[[],[],[]];active=null;renderCards();updateProgress();show('cardStage');$('#stepText').textContent='第一步 · 选择卡牌'}
$('#restart').onclick=reset;$('#restartTop').onclick=reset;$('#saveResult').onclick=()=>toast('当前版本请使用系统截图保存，正式版可接入一键海报');function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}renderCards();updateProgress();
